spring:
  profiles:
    active: local

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secretKey: dfjklaefjlaejfdcDfejA123idjfW123oidfRtestHfdjaidfRRtest12T3413dfjladfaeDFADFAdfvdsAERdfAERad12ADFerDFAvEFDF
  algorithm: HS512

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/daycare
    username: sa
    password: test
    #    password:
    driver-class-name: org.h2.Driver