spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/daycare
    username: sa
    password: test
#    password:
    driver-class-name: org.h2.Driver

